# Generated by Django 4.2.28 on 2026-02-27 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='blog.comment'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'post', 'comment')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='reply',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
