# Generated by Django 4.2.28 on 2026-02-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_vote_unique_together_vote_comment_and_more'),
    ]

    operations = []
