# Generated by Django 4.2.28 on 2026-02-27 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_resource_comment_alter_resource_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='blog.comment'),
        ),
    ]
