# Generated by Django 4.2.28 on 2026-03-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_tag_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='blog.tag'),
        ),
    ]
