# Generated by Django 4.2.28 on 2026-03-02 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_subject_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='blog.subject'),
        ),
    ]
