# Generated by Django 4.2.28 on 2026-03-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_resource_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
