# Generated by Django 4.2.28 on 2026-03-02 18:02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_subject_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='short_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
