# Generated by Django 4.2.28 on 2026-03-02 18:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_subject_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='short_description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
