# Generated by Django 4.2.28 on 2026-03-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_subject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.subject'),
            preserve_default=False,
        ),
    ]
