# Generated by Django 4.2.28 on 2026-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_comment_created_on_alter_like_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
