# Generated by Django 4.2.28 on 2026-03-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_like_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
